### ISSUE TITLE
dplyr::lag() instead of lag()

### ISSUE THREAD

**Issue by n3ssuno** [DSoudis/shiftshare#1]
Hi, thanks for your package!
I think I've found a small bug in the dynamic functions of the dynamic_ssa.R file.
Where you call lag() I suppose it should be dplyr::lag(), otherwise if you haven't loaded the dplyr library the subtraction will produce 0s.
Let me know what do you think about that and thanks again.

**Comment by DSoudis** [comment]
Hi n3ssuno!
Spot on! I pushed the changes needed and it worked fine for me now!
Thanks for catching this!

**Comment by n3ssuno** [comment]
Happy to have helped you and thanks for the useful package!
